
class SrtConstants:

    ENCODING_UTF_8_SIG = "utf-8-sig"
    ENCODING_UTF_8 = "utf-8"
    ENCODING_CP1252 = "cp1252"
    SRT_ENCODINGS = [ENCODING_UTF_8_SIG, ENCODING_UTF_8, ENCODING_CP1252]

    TIMESTAMP_START = "start"
    TIMESTAMP_END = "end"

    MINS_UPPER_LIMIT = 59
    SECS_UPPER_LIMIT = 59
    MS_UPPER_LIMIT = 999

    MS_PER_HOUR = 3_600_000
    MS_PER_MINUTE = 60_000
    MS_PER_SECOND = 1000

    VERIFIED_SPEAKER_CONFIDENCE = 1.0