"""Non-secret policy for the v1 third-adjudication review host boundary."""

from __future__ import annotations

from pathlib import Path
from typing import Final

from scripts.private_speaker_review_first_adjudication_observation_host_contract import (
    BOOTSTRAP_COMMANDS,
    CINEGRAPH_IMAGE_REVISION_LABEL,
    CINEGRAPH_IMAGE_SOURCE,
    CINEGRAPH_IMAGE_SOURCE_LABEL,
    CINEGRAPH_IMAGE_VERSION_LABEL,
    CLIENT_TIMEOUT_MARGIN_SECONDS,
    CURRENT_LINK,
    DEPLOY_ROOT,
    DEPLOYMENT_LOCK,
    ENV_FILE,
    GID_IN_CONTAINER,
    RELEASES_ROOT,
    REPOSITORY_URL,
    REVIEW_AUTHORIZATION_ROOT,
    REVIEW_AUTHORIZED_KEYS,
    REVIEW_DISPATCH_PATH,
    REVIEW_FIRST_ADJUDICATION_OBSERVATION_RECEIPTS_ROOT,
    REVIEW_GROUP,
    REVIEW_HOME,
    REVIEW_PASSWORD_FIELD,
    REVIEW_SHELL,
    REVIEW_SUBMISSION_RECEIPTS_ROOT,
    REVIEW_UID,
    REVIEW_USER,
    SHARED_ROOT,
    SPEAKER_REVIEW_LOCK,
    SPEAKER_REVIEW_ROOT,
    SPEAKER_REVIEW_RUNS_ROOT,
    TRANSFER_LOCK,
    UID_IN_CONTAINER,
    authorized_key_entry,
)
from scripts.private_speaker_review_next_adjudication_observation_host_contract import (
    SUDOERS_CONTENT as PHASE72_SUDOERS_CONTENT,
)

REVIEW_THIRD_ADJUDICATION_COMMAND: Final = "speaker-review-submit-third-adjudication-v1"
REVIEW_THIRD_ADJUDICATION_HELPER_PATH: Final = Path(
    "/usr/local/sbin/cinegraph-submit-third-private-speaker-review-adjudication"
)
REVIEW_THIRD_ADJUDICATION_RECEIPTS_ROOT: Final = (
    SPEAKER_REVIEW_ROOT / "third-adjudication-submission-receipts"
)
REVIEW_THIRD_ADJUDICATION_COMPOSE_PROFILE: Final = (
    "corpus-speaker-review-submit-third-adjudication"
)
REVIEW_THIRD_ADJUDICATION_COMPOSE_SERVICE: Final = REVIEW_THIRD_ADJUDICATION_COMPOSE_PROFILE
REVIEW_THIRD_ADJUDICATION_COMPOSE_PROJECT: Final = "cinegraph-dev"
REVIEW_THIRD_ADJUDICATION_CONTAINER_NAME: Final = (
    "cinegraph-speaker-review-submit-third-adjudication"
)
REVIEW_THIRD_ADJUDICATION_CONTAINER_WORKDIR: Final = "/app"
REVIEW_THIRD_ADJUDICATION_CONTAINER_COMMAND: Final = (
    "python",
    "scripts/submit_third_private_speaker_review_adjudication_workspace.py",
)
REVIEW_THIRD_ADJUDICATION_NETWORK: Final = (
    f"{REVIEW_THIRD_ADJUDICATION_COMPOSE_PROJECT}_egress"
)
REVIEW_THIRD_ADJUDICATION_TIMEOUT_SECONDS: Final = 1800
REVIEW_THIRD_ADJUDICATION_KILL_AFTER_SECONDS: Final = 10
REVIEW_THIRD_ADJUDICATION_WORKER_UID: Final = UID_IN_CONTAINER
REVIEW_THIRD_ADJUDICATION_WORKER_GID: Final = GID_IN_CONTAINER
REVIEW_THIRD_ADJUDICATION_RUNS_MOUNT: Final = Path("/review-workspace/review-runs")
REVIEW_THIRD_ADJUDICATION_RUNS_TARGET: Final = REVIEW_THIRD_ADJUDICATION_RUNS_MOUNT
REVIEW_THIRD_ADJUDICATION_SECRET_TARGET: Final = "/run/secrets/openai_api_key"
REVIEW_THIRD_ADJUDICATION_TMP_TARGET: Final = "/tmp"  # nosec B108

# Phase 73 adds exactly one no-argument root helper after the Phase 72 policy.
SUDOERS_CONTENT: Final = (
    PHASE72_SUDOERS_CONTENT
    + f'{REVIEW_USER} ALL=(root) NOPASSWD: {REVIEW_THIRD_ADJUDICATION_HELPER_PATH.as_posix()} ""\n'
)

__all__ = [
    "BOOTSTRAP_COMMANDS",
    "CINEGRAPH_IMAGE_REVISION_LABEL",
    "CINEGRAPH_IMAGE_SOURCE",
    "CINEGRAPH_IMAGE_SOURCE_LABEL",
    "CINEGRAPH_IMAGE_VERSION_LABEL",
    "CLIENT_TIMEOUT_MARGIN_SECONDS",
    "CURRENT_LINK",
    "DEPLOYMENT_LOCK",
    "DEPLOY_ROOT",
    "ENV_FILE",
    "GID_IN_CONTAINER",
    "RELEASES_ROOT",
    "REPOSITORY_URL",
    "REVIEW_AUTHORIZATION_ROOT",
    "REVIEW_AUTHORIZED_KEYS",
    "REVIEW_DISPATCH_PATH",
    "REVIEW_FIRST_ADJUDICATION_OBSERVATION_RECEIPTS_ROOT",
    "REVIEW_GROUP",
    "REVIEW_HOME",
    "REVIEW_PASSWORD_FIELD",
    "REVIEW_SHELL",
    "REVIEW_SUBMISSION_RECEIPTS_ROOT",
    "REVIEW_UID",
    "REVIEW_USER",
    "SHARED_ROOT",
    "SPEAKER_REVIEW_LOCK",
    "SPEAKER_REVIEW_ROOT",
    "SPEAKER_REVIEW_RUNS_ROOT",
    "TRANSFER_LOCK",
    "UID_IN_CONTAINER",
    "authorized_key_entry",
    "REVIEW_THIRD_ADJUDICATION_COMMAND",
    "REVIEW_THIRD_ADJUDICATION_HELPER_PATH",
    "REVIEW_THIRD_ADJUDICATION_RECEIPTS_ROOT",
    "REVIEW_THIRD_ADJUDICATION_COMPOSE_PROFILE",
    "REVIEW_THIRD_ADJUDICATION_COMPOSE_SERVICE",
    "REVIEW_THIRD_ADJUDICATION_COMPOSE_PROJECT",
    "REVIEW_THIRD_ADJUDICATION_CONTAINER_NAME",
    "REVIEW_THIRD_ADJUDICATION_CONTAINER_WORKDIR",
    "REVIEW_THIRD_ADJUDICATION_CONTAINER_COMMAND",
    "REVIEW_THIRD_ADJUDICATION_NETWORK",
    "REVIEW_THIRD_ADJUDICATION_TIMEOUT_SECONDS",
    "REVIEW_THIRD_ADJUDICATION_KILL_AFTER_SECONDS",
    "REVIEW_THIRD_ADJUDICATION_WORKER_UID",
    "REVIEW_THIRD_ADJUDICATION_WORKER_GID",
    "REVIEW_THIRD_ADJUDICATION_RUNS_MOUNT",
    "REVIEW_THIRD_ADJUDICATION_RUNS_TARGET",
    "REVIEW_THIRD_ADJUDICATION_SECRET_TARGET",
    "REVIEW_THIRD_ADJUDICATION_TMP_TARGET",
    "SUDOERS_CONTENT",
]
