"""Non-secret policy for the v1 next-primary review host boundary."""

from __future__ import annotations

from pathlib import Path
from typing import Final

from scripts.private_corpus_host_contract import (
    CINEGRAPH_IMAGE_REVISION_LABEL,
    CINEGRAPH_IMAGE_SOURCE,
    CINEGRAPH_IMAGE_SOURCE_LABEL,
    CINEGRAPH_IMAGE_VERSION_LABEL,
)
from scripts.private_speaker_review_observation_host_contract import (
    REVIEW_OBSERVATION_RECEIPTS_ROOT,
)
from scripts.private_speaker_review_submission_host_contract import (
    BOOTSTRAP_COMMANDS,
    CLIENT_TIMEOUT_MARGIN_SECONDS,
    CURRENT_LINK,
    DEPLOY_ROOT,
    DEPLOYMENT_LOCK,
    ENV_FILE,
    RELEASES_ROOT,
    REPOSITORY_URL,
    REVIEW_AUTHORIZATION_ROOT,
    REVIEW_AUTHORIZED_KEYS,
    REVIEW_DISPATCH_PATH,
    REVIEW_GROUP,
    REVIEW_HELPER_PATH,
    REVIEW_HOME,
    REVIEW_OBSERVATION_HELPER_PATH,
    REVIEW_PASSWORD_FIELD,
    REVIEW_SHELL,
    REVIEW_SUBMISSION_RECEIPTS_ROOT,
    REVIEW_UID,
    REVIEW_USER,
    SHARED_ROOT,
    SPEAKER_REVIEW_LOCK,
    SPEAKER_REVIEW_ROOT,
    SPEAKER_REVIEW_RUNS_ROOT,
    TRANSFER_LOCK,
    authorized_key_entry,
)
from scripts.private_speaker_review_submission_host_contract import (
    SUDOERS_CONTENT as OBSERVATION_SUDOERS_CONTENT,
)

REVIEW_NEXT_PRIMARY_COMMAND: Final = "speaker-review-submit-next-primary-v1"
REVIEW_NEXT_PRIMARY_HELPER_PATH: Final = Path(
    "/usr/local/sbin/cinegraph-submit-next-private-speaker-review"
)
REVIEW_NEXT_PRIMARY_RECEIPTS_ROOT: Final = SPEAKER_REVIEW_ROOT / "next-primary-receipts"
REVIEW_NEXT_PRIMARY_CONTAINER_NAME: Final = "cinegraph-speaker-review-submit-next-primary"
REVIEW_NEXT_PRIMARY_COMPOSE_SERVICE: Final = "corpus-speaker-review-submit-next-primary"
REVIEW_NEXT_PRIMARY_COMPOSE_PROFILE: Final = REVIEW_NEXT_PRIMARY_COMPOSE_SERVICE
REVIEW_NEXT_PRIMARY_COMPOSE_PROJECT: Final = "cinegraph-dev"
REVIEW_NEXT_PRIMARY_NETWORK: Final = f"{REVIEW_NEXT_PRIMARY_COMPOSE_PROJECT}_egress"
REVIEW_NEXT_PRIMARY_TIMEOUT_SECONDS: Final = 1800
REVIEW_NEXT_PRIMARY_KILL_AFTER_SECONDS: Final = 10
REVIEW_NEXT_PRIMARY_CONTAINER_WORKDIR: Final = "/app"
REVIEW_NEXT_PRIMARY_CONTAINER_COMMAND: Final = (
    "python",
    "scripts/submit_next_private_speaker_review_workspace.py",
)
REVIEW_NEXT_PRIMARY_SECRET_TARGET: Final = "/run/secrets/openai_api_key"
# Fixed in-container tmpfs destination; this is not a host temporary-file path.
REVIEW_NEXT_PRIMARY_TMP_TARGET: Final = "/tmp"  # nosec B108
UID_IN_CONTAINER: Final = 10002
GID_IN_CONTAINER: Final = 10002

SUDOERS_CONTENT: Final = (
    OBSERVATION_SUDOERS_CONTENT
    + f'{REVIEW_USER} ALL=(root) NOPASSWD: {REVIEW_NEXT_PRIMARY_HELPER_PATH.as_posix()} ""\n'
)

__all__ = [
    "BOOTSTRAP_COMMANDS",
    "CLIENT_TIMEOUT_MARGIN_SECONDS",
    "CURRENT_LINK",
    "DEPLOY_ROOT",
    "DEPLOYMENT_LOCK",
    "ENV_FILE",
    "RELEASES_ROOT",
    "REPOSITORY_URL",
    "REVIEW_AUTHORIZATION_ROOT",
    "REVIEW_AUTHORIZED_KEYS",
    "REVIEW_DISPATCH_PATH",
    "REVIEW_GROUP",
    "REVIEW_HELPER_PATH",
    "REVIEW_HOME",
    "REVIEW_OBSERVATION_HELPER_PATH",
    "REVIEW_OBSERVATION_RECEIPTS_ROOT",
    "REVIEW_PASSWORD_FIELD",
    "REVIEW_SHELL",
    "REVIEW_SUBMISSION_RECEIPTS_ROOT",
    "REVIEW_UID",
    "REVIEW_USER",
    "SHARED_ROOT",
    "SPEAKER_REVIEW_LOCK",
    "SPEAKER_REVIEW_ROOT",
    "SPEAKER_REVIEW_RUNS_ROOT",
    "TRANSFER_LOCK",
    "REVIEW_NEXT_PRIMARY_COMMAND",
    "REVIEW_NEXT_PRIMARY_HELPER_PATH",
    "REVIEW_NEXT_PRIMARY_RECEIPTS_ROOT",
    "REVIEW_NEXT_PRIMARY_CONTAINER_NAME",
    "REVIEW_NEXT_PRIMARY_COMPOSE_SERVICE",
    "REVIEW_NEXT_PRIMARY_COMPOSE_PROFILE",
    "REVIEW_NEXT_PRIMARY_COMPOSE_PROJECT",
    "REVIEW_NEXT_PRIMARY_NETWORK",
    "REVIEW_NEXT_PRIMARY_TIMEOUT_SECONDS",
    "REVIEW_NEXT_PRIMARY_KILL_AFTER_SECONDS",
    "CINEGRAPH_IMAGE_REVISION_LABEL",
    "CINEGRAPH_IMAGE_SOURCE",
    "CINEGRAPH_IMAGE_SOURCE_LABEL",
    "CINEGRAPH_IMAGE_VERSION_LABEL",
    "REVIEW_NEXT_PRIMARY_CONTAINER_COMMAND",
    "REVIEW_NEXT_PRIMARY_CONTAINER_WORKDIR",
    "REVIEW_NEXT_PRIMARY_SECRET_TARGET",
    "REVIEW_NEXT_PRIMARY_TMP_TARGET",
    "UID_IN_CONTAINER",
    "GID_IN_CONTAINER",
    "SUDOERS_CONTENT",
    "authorized_key_entry",
]
