"""Centralized host policy for observing exactly adjudication part four."""

from __future__ import annotations

from pathlib import Path
from typing import Final

from scripts.private_speaker_review_first_adjudication_observation_host_contract import (
    CINEGRAPH_IMAGE_REVISION_LABEL,
    CINEGRAPH_IMAGE_SOURCE,
    CINEGRAPH_IMAGE_SOURCE_LABEL,
    CINEGRAPH_IMAGE_VERSION_LABEL,
)
from scripts.private_speaker_review_fourth_adjudication_host_contract import (
    REVIEW_FOURTH_ADJUDICATION_RECEIPTS_ROOT as REVIEW_FOURTH_ADJUDICATION_SUBMISSION_RECEIPTS_ROOT,
)
from scripts.private_speaker_review_fourth_adjudication_host_contract import (
    SUDOERS_CONTENT as PHASE75_SUDOERS_CONTENT,
)
from scripts.private_speaker_review_observation_host_contract import (
    GID_IN_CONTAINER,
    REVIEW_OBSERVATION_TIMEOUT_SECONDS,
    UID_IN_CONTAINER,
)
from scripts.private_speaker_review_submission_host_contract import (
    BOOTSTRAP_COMMANDS,
    CLIENT_TIMEOUT_MARGIN_SECONDS,
    CURRENT_LINK,
    DEPLOY_ROOT,
    DEPLOYMENT_LOCK,
    ENV_FILE,
    RELEASES_ROOT,
    REPOSITORY_URL,
    REVIEW_AUTHORIZATION_ROOT,
    REVIEW_AUTHORIZED_KEYS,
    REVIEW_DISPATCH_PATH,
    REVIEW_GROUP,
    REVIEW_HOME,
    REVIEW_PASSWORD_FIELD,
    REVIEW_SHELL,
    REVIEW_SUBMISSION_RECEIPTS_ROOT,
    REVIEW_UID,
    REVIEW_USER,
    SHARED_ROOT,
    SPEAKER_REVIEW_LOCK,
    SPEAKER_REVIEW_ROOT,
    SPEAKER_REVIEW_RUNS_ROOT,
    TRANSFER_LOCK,
    authorized_key_entry,
)

REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMMAND: Final = (
    "speaker-review-observe-fourth-adjudication-v1"
)
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_HELPER_PATH: Final = Path(
    "/usr/local/sbin/cinegraph-observe-fourth-private-speaker-review-adjudication"
)
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_RECEIPTS_ROOT: Final = (
    SPEAKER_REVIEW_ROOT / "fourth-adjudication-observation-receipts"
)
# The predecessor's root receipt is intentionally distinct from this
# operation's receipt directory.
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMPOSE_PROFILE: Final = (
    "corpus-speaker-review-observe-fourth-adjudication"
)
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMPOSE_SERVICE: Final = (
    REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMPOSE_PROFILE
)
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMPOSE_PROJECT: Final = "cinegraph-dev"
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_CONTAINER_NAME: Final = (
    "cinegraph-speaker-review-observe-fourth-adjudication"
)
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_TIMEOUT_SECONDS: Final = REVIEW_OBSERVATION_TIMEOUT_SECONDS
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_KILL_AFTER_SECONDS: Final = 10
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_CONTAINER_WORKDIR: Final = "/app"
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_CONTAINER_COMMAND: Final = (
    "python",
    "scripts/observe_fourth_private_speaker_review_adjudication_workspace.py",
)
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_NETWORK: Final = "cinegraph-dev_egress"
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_SECRET_TARGET: Final = "/run/secrets/openai_api_key"
REVIEW_FOURTH_ADJUDICATION_OBSERVATION_TMP_TARGET: Final = "/tmp"  # nosec B108
SUDOERS_CONTENT: Final = (
    PHASE75_SUDOERS_CONTENT + f"{REVIEW_USER} ALL=(root) NOPASSWD: "
    f'{REVIEW_FOURTH_ADJUDICATION_OBSERVATION_HELPER_PATH.as_posix()} ""\n'
)

__all__ = [
    "BOOTSTRAP_COMMANDS",
    "CINEGRAPH_IMAGE_REVISION_LABEL",
    "CINEGRAPH_IMAGE_SOURCE",
    "CINEGRAPH_IMAGE_SOURCE_LABEL",
    "CINEGRAPH_IMAGE_VERSION_LABEL",
    "CLIENT_TIMEOUT_MARGIN_SECONDS",
    "CURRENT_LINK",
    "DEPLOYMENT_LOCK",
    "DEPLOY_ROOT",
    "ENV_FILE",
    "GID_IN_CONTAINER",
    "RELEASES_ROOT",
    "REPOSITORY_URL",
    "REVIEW_AUTHORIZATION_ROOT",
    "REVIEW_AUTHORIZED_KEYS",
    "REVIEW_DISPATCH_PATH",
    "REVIEW_GROUP",
    "REVIEW_HOME",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMMAND",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMPOSE_PROFILE",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMPOSE_PROJECT",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_COMPOSE_SERVICE",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_CONTAINER_COMMAND",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_CONTAINER_NAME",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_CONTAINER_WORKDIR",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_HELPER_PATH",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_KILL_AFTER_SECONDS",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_NETWORK",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_RECEIPTS_ROOT",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_SECRET_TARGET",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_TMP_TARGET",
    "REVIEW_FOURTH_ADJUDICATION_OBSERVATION_TIMEOUT_SECONDS",
    "REVIEW_FOURTH_ADJUDICATION_SUBMISSION_RECEIPTS_ROOT",
    "REVIEW_PASSWORD_FIELD",
    "REVIEW_SHELL",
    "REVIEW_SUBMISSION_RECEIPTS_ROOT",
    "REVIEW_UID",
    "REVIEW_USER",
    "SHARED_ROOT",
    "SPEAKER_REVIEW_LOCK",
    "SPEAKER_REVIEW_ROOT",
    "SPEAKER_REVIEW_RUNS_ROOT",
    "TRANSFER_LOCK",
    "SUDOERS_CONTENT",
    "UID_IN_CONTAINER",
    "authorized_key_entry",
]
