"""Non-secret contract for the bounded primary-observation host boundary."""

from __future__ import annotations

from typing import Final

from scripts.private_corpus_host_contract import MINIMUM_PYTHON_VERSION
from scripts.private_speaker_review_submission_host_contract import (
    CLIENT_TIMEOUT_MARGIN_SECONDS,
    CURRENT_LINK,
    DEPLOY_ROOT,
    ENV_FILE,
    RELEASES_ROOT,
    REPOSITORY_URL,
    REVIEW_AUTHORIZATION_ROOT,
    REVIEW_AUTHORIZED_KEYS,
    REVIEW_DISPATCH_PATH,
    REVIEW_GID,
    REVIEW_GROUP,
    REVIEW_HOME,
    REVIEW_OBSERVATION_COMMAND,
    REVIEW_OBSERVATION_HELPER_PATH,
    REVIEW_PASSWORD_FIELD,
    REVIEW_SHELL,
    REVIEW_SUBMISSION_RECEIPTS_ROOT,
    REVIEW_UID,
    REVIEW_USER,
    SHARED_ROOT,
    SPEAKER_REVIEW_LOCK,
    SPEAKER_REVIEW_ROOT,
    TRANSFER_LOCK,
)

REVIEW_OBSERVATION_RECEIPTS_ROOT: Final = SPEAKER_REVIEW_ROOT / "observation-receipts"
REVIEW_OBSERVATION_CONTAINER_NAME: Final = "cinegraph-speaker-review-observe-primary"
REVIEW_OBSERVATION_TIMEOUT_SECONDS: Final = 1800
REVIEW_OBSERVATION_KILL_AFTER_SECONDS: Final = 10
UID_IN_CONTAINER: Final = 10002
GID_IN_CONTAINER: Final = 10002

__all__ = [
    "DEPLOY_ROOT",
    "ENV_FILE",
    "GID_IN_CONTAINER",
    "RELEASES_ROOT",
    "CURRENT_LINK",
    "CLIENT_TIMEOUT_MARGIN_SECONDS",
    "MINIMUM_PYTHON_VERSION",
    "REPOSITORY_URL",
    "REVIEW_AUTHORIZATION_ROOT",
    "REVIEW_AUTHORIZED_KEYS",
    "REVIEW_DISPATCH_PATH",
    "REVIEW_GID",
    "REVIEW_GROUP",
    "REVIEW_HOME",
    "REVIEW_OBSERVATION_COMMAND",
    "REVIEW_OBSERVATION_CONTAINER_NAME",
    "REVIEW_OBSERVATION_HELPER_PATH",
    "REVIEW_OBSERVATION_KILL_AFTER_SECONDS",
    "REVIEW_OBSERVATION_RECEIPTS_ROOT",
    "REVIEW_OBSERVATION_TIMEOUT_SECONDS",
    "REVIEW_PASSWORD_FIELD",
    "REVIEW_SHELL",
    "REVIEW_SUBMISSION_RECEIPTS_ROOT",
    "REVIEW_UID",
    "REVIEW_USER",
    "SHARED_ROOT",
    "SPEAKER_REVIEW_LOCK",
    "SPEAKER_REVIEW_ROOT",
    "TRANSFER_LOCK",
    "UID_IN_CONTAINER",
]
